// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Norm;
using FluentAssertions;
using CompaniesDb.Extensions;
using CompaniesWebBlazor.Shared;

namespace CompaniesDbTests
{
    public class DeleteCompanyUnitTests : PostgreSqlUnitTestFixture
    {
        public DeleteCompanyUnitTests(PostgreSqlFixture fixture) : base(fixture) { }

        [Fact]
        public void DeleteCompany_Test1()
        {
            // Arrange
            var model = new Company { Name = "n", NameNormalized = "nn", About = "about", AreaId = 1, Website = "website" };
            var result = Connection.CreateCompanyOnConflictDoUpdateReturning(model);

            // Act
            Connection.DeleteCompany(result);

            // Assert
            Assert.False(Connection.Read($"select * from {CompanyDelete.Name} where id = {result.Id}").Any());
        }
    }
}
