// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Norm;
using FluentAssertions;
using CompaniesDb.Extensions;
using CompaniesDb.Models;

namespace CompaniesDbTests
{
    public class ReadCompanyByIdUnitTests : PostgreSqlUnitTestFixture
    {
        public ReadCompanyByIdUnitTests(PostgreSqlFixture fixture) : base(fixture) { }

        [Fact]
        public void ReadCompanyById_Test1()
        {
            // Arrange
            var model = Connection.CreateCompanyOnConflictDoUpdateReturning(new Company { Name = "n", NameNormalized = "nn", About = "about", AreaId = 1, Website = "website" });

            // Act
            var result = Connection.ReadCompanyById(model.Id);

            // Assert
            model.Should().BeEquivalentTo(result);
        }
    }
}
