// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Norm;
using NpgsqlTypes;
using Npgsql;
using CompaniesDb.Models;

namespace CompaniesDb.Extensions
{
    public static class CompanyAreaReadAll
    {
        public const string Name = "company_areas";

        public const string Sql = @"
            SELECT
                ""id"",
                ""name""
            FROM
                ""company_areas""";

        /// <summary>
        /// Select table ""company_areas"" and return enumerator of instances of a "CompaniesDb.Extensions.CompanyArea" class.
        /// </summary>
        /// <returns>Single instance of a "CompaniesDb.Extensions.CompanyArea" class that is mapped to resulting record of table ""company_areas""</returns>
        public static IEnumerable<CompanyArea> ReadCompanyAreaAll(this NpgsqlConnection connection)
        {
            return connection
                .Prepared()
                .Read<CompanyArea>(Sql);
        }

        /// <summary>
        /// Asynchronously select table ""company_areas"" and return enumerator of instances of a "CompanyArea" class.
        /// </summary>
        /// <returns>IAsyncEnumerable of "CompaniesDb.Extensions.CompanyArea" instances.</returns>
        public static IAsyncEnumerable<CompanyArea> ReadCompanyAreaAllAsync(this NpgsqlConnection connection)
        {
            return connection
                .Prepared()
                .ReadAsync<CompanyArea>(Sql);
        }
    }
}
