// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;

namespace CompaniesDb.Models
{
    public class Company
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string NameNormalized { get; set; }
        public string Website { get; set; }
        public int AreaId { get; set; }
        public string About { get; set; }
        public DateTime Modified { get; set; }
    }
}
