// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;

namespace CompaniesDb.Models
{
    public class CompanyArea
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
