// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Norm;
using NpgsqlTypes;
using Npgsql;
using CompaniesWebBlazor.Shared;

namespace CompaniesDb.Extensions
{
    public static class CompanyDeleteBy
    {
        public const string Name = "companies";

        public const string Sql = @"
            DELETE FROM ""companies""
            WHERE
                ""id"" = @id";

        /// <summary>
        ///  Delete record of table ""companies"" by primary keys.
        /// </summary>
        /// <param name="id">Select table ""companies"" where field id bigint is this value.</param>
        public static void DeleteCompanyById(this NpgsqlConnection connection, long id)
        {
            connection
                .Prepared()
                .Execute(Sql, 
                    ("id", id, NpgsqlDbType.Bigint));
        }

        /// <summary>
        /// Asynchronously delete record of table ""companies"" by primary keys.
        /// </summary>
        /// <param name="id">Select table ""companies"" where field id bigint is this value.</param>
        public static async void DeleteCompanyByIdAsync(this NpgsqlConnection connection, long id)
        {
            await connection
                .Prepared()
                .ExecuteAsync(Sql, 
                    ("id", id, NpgsqlDbType.Bigint));
        }
    }
}
