// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Norm;
using NpgsqlTypes;
using Npgsql;
using CompaniesWebBlazor.Shared;

namespace CompaniesDb.Extensions
{
    public static class CompaniesDelete
    {
        public const string Name = "companies";

        public const string Sql = @"
            DELETE FROM ""companies""
            WHERE
                ""id"" = @id";

        /// <summary>
        /// Delete record of table ""companies"" by matching values of key fields: id
        /// </summary>
        /// <param name="model">Instance of a "CompaniesDb.Extensions.Company" model class.</param>
        public static void DeleteCompanies(this NpgsqlConnection connection, Company model)
        {
            connection
                .Prepared()
                .Execute(Sql, 
                    ("id", model.Id, NpgsqlDbType.Bigint));
        }

        /// <summary>
        /// Delete record of table ""companies"" by matching values of key fields: id
        /// </summary>
        /// <param name="model">Instance of a "CompaniesDb.Extensions.Company" model class.</param>
        public static async ValueTask DeleteCompaniesAsync(this NpgsqlConnection connection, Company model)
        {
            await connection
                .Prepared()
                .ExecuteAsync(Sql, 
                    ("id", model.Id, NpgsqlDbType.Bigint));
        }
    }
}
